name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: rust
      id: rust
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: rust
        setup-command: sudo apt-get update && sudo apt-get install rustc cargo --fix-missing
        command: cargo test
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUST_RESULTS: "${{steps.rust.outputs.result}}"
      with:
        runners: rust
